apiVersion: v1
kind: Pod
metadata: # Metadados do Pod, informações internad do cluster.
  name: mongodb-pod # Nome interno do Pod, máximo de 15 caracteres.
spec: # Definição do comportamento do Pod
  containers: # Definição do container (Docker ou similar) que será executado dentro do Pod
    - name: mongodb # Nome do container
      image: mongo # Nome da imagem do container
      ports:
      - containerPort: 27017 # Porta interna do container
      resources:
      - requests: # Mínimo necessário para a execução
        - cpu: 100m # 100 milicores, 10% da fração de um core
          memory: 200m
      - limits: # Máximo permitido para uso
        - cpu: 200m
          memory: 500m
